# Generated by Django 2.2.4 on 2019-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salery',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
